version: 1.0.{build}
environment:
  deploy_account_key_secret:
    secure: TT27pcULTwrBGqM4TQJMet1UIGAsKg/WngbZ1VhxkUyz9LQu/zI4z6UNQswHjZE3
before_build:
- ps: nuget restore
build:
  publish_wap: true
  verbosity: minimal
deploy:
- provider: S3
  access_key_id: AKIAIYG6YT3U6WWX4T2A
  secret_access_key:
    secure: 3IJqfSfdpO09A+w7cJ8CgCUt9GnWk3Hia1+mlkkk+TM=
  region: eu-west-1
  bucket: ssa_web_deploy
  artifact: StochasticSimulation.ChemicalKinetics.Web.zip
